server.port: 8080

logging.level.com.example.demo.CustomerClient: DEBUG
logging.level.com.example.demo.AddressClient: DEBUG
logging.level.org.hibernate.SQL: DEBUG

customers:
  ribbon:
    eureka:
      enabled: false
    listOfServers: localhost:8081

addresses:
  ribbon:
    eureka:
      enabled: false
    listOfServers: localhost:8081

spring:
  output:
    ansi:
      enabled: always
