version: '2.1'

services:
  db:
    image: postgres:12.0-alpine
    container_name: local-postgres
    environment:
      POSTGRES_PASSWORD: 'R6&)4#pg{G'
      POSTGRES_USER: raika
    expose:
      - 5432
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U raika -d raika"]
      interval: 5s
      timeout: 31s
      retries: 6